### ISSUE TITLE
Do you have any plans to support React format styles as well?

### ISSUE THREAD

**Issue by subhojit777** [noraesae/react-attr-converter#2]

**Comment by subhojit777** [comment]
I can create a pull request that would support styling also. But it's the name of the module that concerns me.

**Comment by subhojit777** [comment]
@noraesae ping

**Comment by noraesae** [comment]
I'm not sure about what React format styles are. Can you give me an example?

**Comment by subhojit777** [comment]
```json
"class": "className",
"backgound-image": "backgroundImage",
"background-color": "backgroundColor"
```

**Comment by noraesae** [comment]
Oh, now I got it. I think it may become a separated library, as they are not specifically *attributes*. Thanks for your suggestion and really sorry for not accepting it.

**Comment by subhojit777** [comment]
It's okay 😊

**Comment by subhojit777** [comment]
There you go https://www.npmjs.com/package/react-style-converter
