### ISSUE TITLE
Allow "xlink:href" and other attributes with colons

### ISSUE THREAD

**Issue by davidtheclark** [noraesae/react-attr-converter#4]
I see in map.json that `xlinkhref` translates to `xlinkHref`. What about `xlink:href`, which is how I think it would appear in HTML?

Is there a reason I don't understand, or are you open to a PR fixing this?

**Comment by noraesae** [comment]
I'm open to a PR.

**Comment by davidtheclark** [comment]
@noraesae do you know of any reason for having `xlinkhref` without the colon? If not, I'd convert them all to only include the colon version (as in https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/no-unknown-property.js#L99).

**Comment by noraesae** [comment]
Hmm, I think I do not have any reason. I guess `xlink` and `xml` attributes should be with colon. Can you provide a PR?

**Comment by noraesae** [comment]
Released: 0.2.0
